import { AccountType } from '@prisma/client';

export const OHADA_ACCOUNTS = [
    // CLASSE 1 : COMPTES DE RESSOURCES DURABLES
    { number: '101', label: 'Capital social', class: 1, type: AccountType.LIABILITY },
    { number: '1011', label: 'Capital social souscrit, non appelé', class: 1, type: AccountType.LIABILITY },
    { number: '1012', label: 'Capital social souscrit, appelé, non versé', class: 1, type: AccountType.LIABILITY },
    { number: '1013', label: 'Capital social souscrit, appelé, versé, non amorti', class: 1, type: AccountType.LIABILITY },
    { number: '111', label: 'Réserves légales', class: 1, type: AccountType.LIABILITY },
    { number: '112', label: 'Réserves statutaires ou contractuelles', class: 1, type: AccountType.LIABILITY },
    { number: '118', label: 'Autres réserves', class: 1, type: AccountType.LIABILITY },
    { number: '121', label: 'Report à nouveau créditeur', class: 1, type: AccountType.LIABILITY },
    { number: '129', label: 'Report à nouveau débiteur', class: 1, type: AccountType.LIABILITY, normalBalance: 'DEBIT' },
    { number: '131', label: 'Résultat net : Bénéfice', class: 1, type: AccountType.LIABILITY },
    { number: '139', label: 'Résultat net : Perte', class: 1, type: AccountType.LIABILITY, normalBalance: 'DEBIT' },
    { number: '161', label: 'Emprunts obligataires', class: 1, type: AccountType.LIABILITY },
    { number: '162', label: 'Emprunts et dettes auprès des établissements de crédit', class: 1, type: AccountType.LIABILITY },

    // CLASSE 2 : COMPTES D'ACTIF IMMOBILISE
    { number: '211', label: 'Frais de développement', class: 2, type: AccountType.ASSET },
    { number: '212', label: 'Brevets, licences, concessions, marques', class: 2, type: AccountType.ASSET },
    { number: '213', label: 'Logiciels', class: 2, type: AccountType.ASSET },
    { number: '221', label: 'Terrains', class: 2, type: AccountType.ASSET },
    { number: '231', label: 'Bâtiments industriels, agricoles, administratifs', class: 2, type: AccountType.ASSET },
    { number: '241', label: 'Matériel et outillage industriel', class: 2, type: AccountType.ASSET },
    { number: '244', label: 'Matériel de bureau et matériel informatique', class: 2, type: AccountType.ASSET },
    { number: '245', label: 'Matériel de transport', class: 2, type: AccountType.ASSET },
    { number: '281', label: 'Amortissements des immobilisations incorporelles', class: 2, type: AccountType.ASSET, normalBalance: 'CREDIT' },
    { number: '283', label: 'Amortissements des immobilisations corporelles', class: 2, type: AccountType.ASSET, normalBalance: 'CREDIT' },
    { number: '284', label: 'Amortissements du matériel de bureau', class: 2, type: AccountType.ASSET, normalBalance: 'CREDIT' },

    // CLASSE 3 : COMPTES DE STOCKS
    { number: '311', label: 'Marchandises A', class: 3, type: AccountType.ASSET },
    { number: '312', label: 'Marchandises B', class: 3, type: AccountType.ASSET },
    { number: '321', label: 'Matières premières', class: 3, type: AccountType.ASSET },
    { number: '322', label: 'Fournitures consommables', class: 3, type: AccountType.ASSET },
    { number: '331', label: 'Produits en cours', class: 3, type: AccountType.ASSET },
    { number: '361', label: 'Produits finis', class: 3, type: AccountType.ASSET },
    { number: '381', label: 'Marchandises en cours de route', class: 3, type: AccountType.ASSET },

    // CLASSE 4 : COMPTES DE TIERS
    { number: '401', label: 'Fournisseurs, dettes en compte', class: 4, type: AccountType.LIABILITY },
    { number: '4011', label: 'Fournisseurs - Achats de biens et prestations de services', class: 4, type: AccountType.LIABILITY },
    { number: '402', label: 'Fournisseurs, Effets à payer', class: 4, type: AccountType.LIABILITY },
    { number: '408', label: 'Fournisseurs, factures non parvenues', class: 4, type: AccountType.LIABILITY },
    { number: '409', label: 'Fournisseurs, débiteurs', class: 4, type: AccountType.LIABILITY, normalBalance: 'DEBIT' },
    { number: '411', label: 'Clients', class: 4, type: AccountType.ASSET },
    { number: '4111', label: 'Clients - Ventes de biens et prestations de services', class: 4, type: AccountType.ASSET },
    { number: '412', label: 'Clients, Effets à recevoir', class: 4, type: AccountType.ASSET },
    { number: '416', label: 'Créances douteuses ou litigieuses', class: 4, type: AccountType.ASSET },
    { number: '418', label: 'Clients, produits à recevoir', class: 4, type: AccountType.ASSET },
    { number: '419', label: 'Clients, créditeurs', class: 4, type: AccountType.ASSET, normalBalance: 'CREDIT' },
    { number: '421', label: 'Personnel, rémunérations dues', class: 4, type: AccountType.LIABILITY },
    { number: '422', label: 'Personnel, rémunérations dues (Dirigeants)', class: 4, type: AccountType.LIABILITY },
    { number: '431', label: 'Sécurité sociale (CNSS)', class: 4, type: AccountType.LIABILITY },
    { number: '441', label: 'État, impôt sur les bénéfices', class: 4, type: AccountType.LIABILITY },
    { number: '442', label: 'État, autres impôts et taxes', class: 4, type: AccountType.LIABILITY },
    { number: '443', label: 'État, TVA facturée', class: 4, type: AccountType.LIABILITY },
    { number: '444', label: 'État, TVA due ou crédit de TVA', class: 4, type: AccountType.LIABILITY },
    { number: '445', label: 'État, TVA récupérable', class: 4, type: AccountType.ASSET },
    { number: '471', label: 'Débiteurs divers', class: 4, type: AccountType.ASSET },
    { number: '472', label: 'Créditeurs divers', class: 4, type: AccountType.LIABILITY },

    // CLASSE 5 : COMPTES DE TRESORERIE
    { number: '501', label: 'Titres de placement', class: 5, type: AccountType.ASSET },
    { number: '511', label: 'Effets à encaisser', class: 5, type: AccountType.ASSET },
    { number: '512', label: 'Effets à l\'encaissement', class: 5, type: AccountType.ASSET },
    { number: '521', label: 'Banques locales', class: 5, type: AccountType.ASSET },
    { number: '531', label: 'Chèques postaux', class: 5, type: AccountType.ASSET },
    { number: '561', label: 'Banques, crédits de trésorerie', class: 5, type: AccountType.LIABILITY },
    { number: '571', label: 'Caisse monnaie nationale', class: 5, type: AccountType.ASSET },
    { number: '572', label: 'Caisse devises', class: 5, type: AccountType.ASSET },
    { number: '581', label: 'Virements de fonds', class: 5, type: AccountType.ASSET },

    // CLASSE 6 : COMPTES DE CHARGES
    { number: '601', label: 'Achats de marchandises', class: 6, type: AccountType.EXPENSE },
    { number: '602', label: 'Achats de matières premières', class: 6, type: AccountType.EXPENSE },
    { number: '603', label: 'Variation de stocks', class: 6, type: AccountType.EXPENSE, normalBalance: 'DEBIT' }, // Peut être créditeur
    { number: '604', label: 'Achats stockés de matières et fournitures', class: 6, type: AccountType.EXPENSE },
    { number: '605', label: 'Autres achats', class: 6, type: AccountType.EXPENSE },
    { number: '606', label: 'Achats non stockés de matières et fournitures', class: 6, type: AccountType.EXPENSE },
    { number: '608', label: 'Achats de fournitures de bureau', class: 6, type: AccountType.EXPENSE },
    { number: '611', label: 'Transport sur achats', class: 6, type: AccountType.EXPENSE },
    { number: '612', label: 'Transport sur ventes', class: 6, type: AccountType.EXPENSE },
    { number: '621', label: 'Sous-traitance générale', class: 6, type: AccountType.EXPENSE },
    { number: '622', label: 'Locations et charges locatives', class: 6, type: AccountType.EXPENSE },
    { number: '623', label: 'Redevances pour brevets, licences', class: 6, type: AccountType.EXPENSE },
    { number: '624', label: 'Entretien, réparations et maintenance', class: 6, type: AccountType.EXPENSE },
    { number: '625', label: 'Primes d\'assurances', class: 6, type: AccountType.EXPENSE },
    { number: '626', label: 'Etudes, recherches et documentation', class: 6, type: AccountType.EXPENSE },
    { number: '627', label: 'Publicité, publications, relations publiques', class: 6, type: AccountType.EXPENSE },
    { number: '628', label: 'Frais de télécommunications', class: 6, type: AccountType.EXPENSE },
    { number: '631', label: 'Frais bancaires', class: 6, type: AccountType.EXPENSE },
    { number: '632', label: 'Rémunérations d\'intermédiaires et honoraires', class: 6, type: AccountType.EXPENSE },
    { number: '641', label: 'Rémunérations du personnel', class: 6, type: AccountType.EXPENSE },
    { number: '646', label: 'Cotisations sociales (Part patronale)', class: 6, type: AccountType.EXPENSE },
    { number: '651', label: 'Impôts et taxes directs', class: 6, type: AccountType.EXPENSE },
    { number: '654', label: 'Autres impôts et taxes', class: 6, type: AccountType.EXPENSE },
    { number: '661', label: 'Charges d\'intérêts', class: 6, type: AccountType.EXPENSE },
    { number: '662', label: 'Escomptes accordés', class: 6, type: AccountType.EXPENSE },
    { number: '663', label: 'Pertes de change', class: 6, type: AccountType.EXPENSE },
    { number: '671', label: 'Dotations aux amortissements d\'exploitation', class: 6, type: AccountType.EXPENSE },
    { number: '681', label: 'Dotations aux provisions d\'exploitation', class: 6, type: AccountType.EXPENSE },
    { number: '691', label: 'Impôt sur le résultat', class: 6, type: AccountType.EXPENSE },

    // CLASSE 7 : COMPTES DE PRODUITS
    { number: '701', label: 'Ventes de marchandises', class: 7, type: AccountType.REVENUE },
    { number: '702', label: 'Ventes de produits finis', class: 7, type: AccountType.REVENUE },
    { number: '703', label: 'Ventes de produits intermédiaires', class: 7, type: AccountType.REVENUE },
    { number: '704', label: 'Ventes de produits résiduels', class: 7, type: AccountType.REVENUE },
    { number: '705', label: 'Travaux facturés', class: 7, type: AccountType.REVENUE },
    { number: '706', label: 'Services vendus', class: 7, type: AccountType.REVENUE },
    { number: '707', label: 'Produits accessoires', class: 7, type: AccountType.REVENUE },
    { number: '711', label: 'Variation des stocks de marchandises', class: 7, type: AccountType.REVENUE, normalBalance: 'CREDIT' }, // Peut être débiteur
    { number: '712', label: 'Variation des stocks de matières premières', class: 7, type: AccountType.REVENUE },
    { number: '721', label: 'Production immobilisée', class: 7, type: AccountType.REVENUE },
    { number: '731', label: 'Subventions d\'exploitation', class: 7, type: AccountType.REVENUE },
    { number: '752', label: 'Reprises sur amortissements', class: 7, type: AccountType.REVENUE },
    { number: '754', label: 'Autres produits de gestion courante', class: 7, type: AccountType.REVENUE },
    { number: '771', label: 'Intérêts créditeurs', class: 7, type: AccountType.REVENUE },
    { number: '772', label: 'Escomptes obtenus', class: 7, type: AccountType.REVENUE },
    { number: '776', label: 'Gains de change', class: 7, type: AccountType.REVENUE },

    // CLASSE 8 : COMPTES DES AUTRES CHARGES ET DES AUTRES PRODUITS (HAO)
    { number: '81', label: 'Valeurs comptables des cessions d\'immobilisations', class: 8, type: AccountType.EXPENSE },
    { number: '82', label: 'Produits des cessions d\'immobilisations', class: 8, type: AccountType.REVENUE },
    { number: '83', label: 'Charges Hors Activités Ordinaires', class: 8, type: AccountType.EXPENSE },
    { number: '84', label: 'Produits Hors Activités Ordinaires', class: 8, type: AccountType.REVENUE },
];
